[default]
src = 'src'
out = 'out'
libs = ['lib']
remappings = [
    '@openzeppelin/=lib/openzeppelin-contracts/'
]
optimizer = true
optimizer_runs = 200

# See more config options https://github.com/gakonst/foundry/tree/master/config